# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WggvpYYfAzAwGwe_k40kWG087ncFnor1
"""

!pip install feedparser

import feedparser
from datetime import datetime

# --- ステップ2: 取得したいRSSフィードの一覧 ---
RSS_FEEDS = {
    "HYPEBEAST JP": "https://hypebeast.com/jp/feed",
    "WWD JAPAN": "https://www.wwdjapan.com/rss",
}

# --- ステップ3: RSSフィードから記事を取得する関数 ---
def fetch_articles(feed_name, feed_url):
    """
    RSSフィードから記事のタイトル、リンク、日付を取得する
    """
    print(f"\n📡 {feed_name} から記事を取得中...")
    print("-" * 60)

    try:
        # RSSフィードを読み込む
        feed = feedparser.parse(feed_url)

        # エラーチェック
        if feed.bozo and not feed.entries:
            print(f"  ❌ エラー: フィードを読み込めませんでした")
            return []

        articles = []

        # 各記事の情報を取り出す
        for entry in feed.entries[:10]:  # 最新10件を取得

            # タイトル
            title = entry.get("title", "タイトルなし")

            # リンク
            link = entry.get("link", "リンクなし")

            # 公開日（フォーマットはサイトによって異なる）
            published = entry.get("published", entry.get("updated", "日付不明"))

            # 要約（あれば）
            summary = entry.get("summary", "")
            # HTMLタグを簡易的に除去
            import re
            summary_clean = re.sub(r"<[^>]+>", "", summary)
            # 長すぎる場合は100文字に切り詰め
            if len(summary_clean) > 100:
                summary_clean = summary_clean[:100] + "..."

            article = {
                "source": feed_name,
                "title": title,
                "link": link,
                "published": published,
                "summary": summary_clean,
            }
            articles.append(article)

            # 結果を表示
            print(f"  📰 {title}")
            print(f"     🔗 {link}")
            print(f"     📅 {published}")
            if summary_clean:
                print(f"     📝 {summary_clean}")
            print()

        print(f"  ✅ {len(articles)}件の記事を取得しました")
        return articles

    except Exception as e:
        print(f"  ❌ エラーが発生しました: {e}")
        return []


# --- ステップ4: 全フィードから記事を取得 ---
def fetch_all():
    """
    登録されている全てのRSSフィードから記事を取得する
    """
    print("=" * 60)
    print("🔄 ファッション記事の自動収集を開始します")
    print(f"   実行日時: {datetime.now().strftime('%Y年%m月%d日 %H:%M')}")
    print("=" * 60)

    all_articles = []

    for feed_name, feed_url in RSS_FEEDS.items():
        articles = fetch_articles(feed_name, feed_url)
        all_articles.extend(articles)

    print("\n" + "=" * 60)
    print(f"📊 合計: {len(all_articles)}件の記事を取得しました")
    print("=" * 60)

    return all_articles


# --- ステップ5: CSV（スプレッドシート）に保存する ---
def save_to_csv(articles, filename="fashion_articles.csv"):
    """
    取得した記事をCSVファイルに保存する
    Google Colabならダウンロードもできます
    """
    import csv

    with open(filename, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=["source", "title", "link", "published", "summary"])
        writer.writeheader()
        writer.writerows(articles)

    print(f"\n💾 {filename} に保存しました！")
    print(f"   Google Colabの場合: 左のファイルアイコンからダウンロードできます")


# --- 実行 ---
if __name__ == "__main__":
    # 全記事を取得
    articles = fetch_all()

    # CSVに保存
    if articles:
        save_to_csv(articles)

    # --- おまけ: Google Colabでダウンロードしたい場合 ---
    # 以下のコメントを外して実行してください
    # from google.colab import files
    # files.download("fashion_articles.csv")

import os
import feedparser
import json
import re
import csv
import urllib.request
from datetime import datetime

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

API_KEY = os.environ.get("ANTHROPIC_API_KEY")

RSS_FEEDS = {
    "HYPEBEAST JP": "https://hypebeast.com/jp/feed",
    "WWD JAPAN": "https://www.wwdjapan.com/rss",
}

def fetch_articles():
    print("=" * 60)
    print("📡 ステップ1: RSSフィードから記事を取得中...")
    print("=" * 60)
    all_articles = []
    for feed_name, feed_url in RSS_FEEDS.items():
        print(f"\n  🔍 {feed_name} を取得中...")
        feed = feedparser.parse(feed_url)
        for entry in feed.entries[:5]:
            title = entry.get("title", "タイトルなし")
            link = entry.get("link", "")
            published = entry.get("published", entry.get("updated", "日付不明"))
            summary_raw = entry.get("summary", "")
            summary_clean = re.sub(r"<[^>]+>", "", summary_raw)[:200]
            all_articles.append({
                "source": feed_name,
                "title": title,
                "link": link,
                "published": published,
                "original_summary": summary_clean,
            })
            print(f"    📰 {title}")
    print(f"\n  ✅ 合計 {len(all_articles)}件の記事を取得しました")
    return all_articles

def call_claude_api(prompt):
    if not API_KEY:
        raise ValueError("ANTHROPIC_API_KEY が設定されていません。環境変数を設定してください。")
    url = "https://api.anthropic.com/v1/messages"
    data = json.dumps({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 1024,
        "messages": [{"role": "user", "content": prompt}]
    }).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "x-api-key": API_KEY,
        "anthropic-version": "2023-06-01",
    }
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode("utf-8"))
            return result["content"][0]["text"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"  ❌ APIエラー: {e.code} - {error_body}")
        return None
    except Exception as e:
        print(f"  ❌ エラー: {e}")
        return None

def analyze_article(article):
    prompt = f"""以下のファッション記事を分析して、JSON形式で結果を返してください。
JSONのみを返し、それ以外のテキストは一切含めないでください。

【記事タイトル】
{article['title']}

【記事の概要】
{article['original_summary']}

【出力するJSON形式】
{{
  "brands": ["記事に登場するブランド名を配列で。なければ空配列"],
  "category": "以下から1つ選択: ストリート / ラグジュアリー / スニーカー / ビューティー / デザイナー / コラボ / ビジネス / カルチャー / その他",
  "summary": "記事の内容を30〜60文字で要約",
  "trend_keywords": ["トレンドキーワードを1〜3個"]
}}"""
    response_text = call_claude_api(prompt)
    if response_text:
        try:
            clean_text = response_text.strip()
            clean_text = re.sub(r"^```json\s*", "", clean_text)
            clean_text = re.sub(r"\s*```$", "", clean_text)
            return json.loads(clean_text)
        except json.JSONDecodeError:
            return None
    return None

def main():
    articles = fetch_articles()
    if not articles:
        print("❌ 記事が取得できませんでした")
        return
    print("\n" + "=" * 60)
    print("🤖 ステップ2: Claude AIで記事を分析中...")
    print("=" * 60)
    analyzed = []
    for i, article in enumerate(articles):
        print(f"\n  [{i+1}/{len(articles)}] 分析中: {article['title'][:40]}...")
        analysis = analyze_article(article)
        if analysis:
            article["brands"] = ", ".join(analysis.get("brands", []))
            article["category"] = analysis.get("category", "その他")
            article["ai_summary"] = analysis.get("summary", "")
            article["trend_keywords"] = ", ".join(analysis.get("trend_keywords", []))
            print(f"    ✅ カテゴリ: {article['category']}")
            print(f"    🏷️ ブランド: {article['brands'] or 'なし'}")
            print(f"    📝 要約: {article['ai_summary']}")
            print(f"    🔑 トレンド: {article['trend_keywords']}")
        else:
            article["brands"] = ""
            article["category"] = "未分類"
            article["ai_summary"] = ""
            article["trend_keywords"] = ""
        analyzed.append(article)
    print("\n" + "=" * 60)
    print("📊 分析結果まとめ")
    print("=" * 60)
    for a in analyzed:
        print(f"\n  📰 {a['title']}")
        print(f"     📂 {a['category']} | 🏷️ {a['brands'] or 'なし'}")
        print(f"     📝 {a['ai_summary']}")
        print(f"     🔗 {a['link']}")
    filename = "fashion_articles_analyzed.csv"
    with open(filename, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=["source","title","link","published","category","brands","ai_summary","trend_keywords"], extrasaction="ignore")
        writer.writeheader()
        writer.writerows(analyzed)
    print(f"\n💾 {filename} に保存しました！")
    return analyzed

articles = main()